c_compiler:                    # [win]
  - m2w64-toolchain            # [win]
  - vs2015                     # [win]
  - vs2015                     # [win]
cxx_compiler:                  # [win]
  - m2w64-toolchain            # [win]
  - vs2015                     # [win]
  - vs2015                     # [win]
python:
  - 2.7
  - 3.5
  - 3.6
vc:                            # [win]
  - 9                          # [win]
  - 14                         # [win]
  - 14                         # [win]
