{% set name = "backports.lzma" %}
{% set version = "0.0.13" %}
{% set sha256 = "50829db66f0445442f6c796bba0ca62d1f87f54760c4682b6d1489e729a43744" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1000
  script:
    - python setup.py build_ext --compiler=mingw32  # [win and py2k]
    - python setup.py install

requirements:
  build:
    - toolchain
    - m2w64-toolchain  # [win and py2k]
    - python
    - libpython        # [win and py2k]
    - backports
    - m2w64-xz 5.2.*   # [win and py2k]
    - xz 5.2.*         # [unix or (win and py3k)]

  run:
    - python
    - backports
    - m2w64-xz 5.2.*   # [win and py27]
    - xz 5.2.*         # [unix or (win and py3k)]

test:
  source_files:
    - test
  imports:
    - backports
    - backports.lzma
  commands:
    - python -m unittest discover -s test

about:
  home: https://github.com/peterjc/backports.lzma
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Backport of Python 3.3's 'lzma' module for XZ/LZMA compressed files.

extra:
  recipe-maintainers:
    - alimanfoo
    - groutr
    - jakirkham
    - peterjc
