{% set name = "backports.lzma" %}
{% set version = "0.0.11" %}
{% set sha256 = "f6d1664285db415649746cfe76b73876908c45da79fe19493d29d1c940677c32" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script:
    - python setup.py build_ext --compiler=mingw32  # [win and py2k]
    - python setup.py install

requirements:
  build:
    - {{ compiler('c') }}        # [not (win and py2k)]
    - {{ compiler('m2w64_c') }}  # [win and py2k]
  host:
    - python
    - libpython                  # [win and py2k]
    - backports
    - m2w64-xz 5.2.*             # [win and py2k]
    - xz                         # [not (win and py2k)]

  run:
    - python
    - backports
    - m2w64-xz 5.2.*             # [win and py27]
    - xz                         # [not (win and py2k)]

test:
  source_files:
    - test
  imports:
    - backports
    - backports.lzma
  commands:
    - python -m unittest discover -s test

about:
  home: https://github.com/peterjc/backports.lzma
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Backport of Python 3.3's 'lzma' module for XZ/LZMA compressed files.

extra:
  recipe-maintainers:
    - alimanfoo
    - groutr
    - jakirkham
    - peterjc
