{% set name = "backports.lzma" %}
{% set version = "0.0.14" %}
{% set sha256 = "16d8b68e4d3cd4e6c9ddb059850452946da3914c8a8e197a7f2b0954559f2df4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 2
  script:
    - {{ PYTHON }} setup.py build_ext --compiler=mingw32 --include-dirs "%LIBRARY_PREFIX%\mingw-w64\include" --library-dirs "%LIBRARY_PREFIX%\mingw-w64\lib"  # [win and py27]
    - {{ PYTHON }} setup.py install

requirements:
  build:
    - {{ compiler('c') }}        # [not (win and py27)]
    - {{ compiler('m2w64_c') }}  # [win and py27]
  host:
    - python
    - libpython                  # [win and py27]
    - backports
    - m2w64-xz 5.2.*             # [win and py27]
    - xz                         # [not (win and py27)]

  run:
    - python
    - backports
    - m2w64-xz 5.2.*             # [win and py27]
    - xz                         # [not (win and py27)]
    - future                     # [py27]

test:
  source_files:
    - test
  imports:
    - backports
    - backports.lzma
  commands:
    - python -m unittest discover -s test

about:
  home: https://github.com/peterjc/backports.lzma
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Backport of Python 3.3's 'lzma' module for XZ/LZMA compressed files.

extra:
  recipe-maintainers:
    - alimanfoo
    - groutr
    - jakirkham
    - peterjc
