appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: abliOQ+devZJIQYcxSwQArnoA2Ln71XMeB5BBJgIBaBc/tgdrQzaIubXoPVMNK+VJE/B3caq5X6Z/woyYKa/6jJo6/mXlWWT5uG+/jA2jTVA4TAPsUv9JSdkIAWdKlJLW5OruPyU8XwCPNZDB4hyPgeycvJ7HCQBrnObPtsqoNm1FdlBDfhNi+Qf1xdbh2QFyFczCClgldmqfbtBSp29E5n84ElN5FNY+IcInbWgMOm77UMz0xUDFQXpi06zx51mBUg5LRq7V14+snWJJ0xBXlgOgPdx/lIUvDn1p37QAWcIc2KrJ5EqXqXXq/cuIGU2nr+IWyfUhf35tJvpi54R1cXEhYUXLYvPxMgQCnTheyc6cr98hnFgrh1Gwxzu8bdkRFcVAgplDLjRDzo54/psD/8FIx7jyx3ETsF5qHxiQAXRdPaEGnUf6Aqh3+xVuT3xX67XJ88GonMtxvkqxS4CslKSPc5vCUciNfnBVcF7o2jWUqIKbti4kwNfreBUHdj/Aj7jRNx/+Un4sUntOoX9NqJ0QH+qBdFzFteeOcEFNn1F9gtmdaYQmufIBXtkbCrKYCwm9thmqPWkSXgQITANzMsaRdWZBCwyqbytq7tPmV1Tb3kpZf1QXuN86i8cK0Htvb7IVwKd6w8siDWcPLccjCSywVdo7STbXb8wpyUCs5k=}
provider:
  win: azure
conda_forge_output_validation: false
